### ISSUE TITLE
Mod missing in new update. (Client)

### ISSUE THREAD

**Issue by 0ExoticMango** [Friskzips/Lc-True-Darkness#1]
If you manually download each version, you can see that in the 1.0.1 zip file version, it's missing the .dll. Meanwhile, the 1.0.0 version has it.
Pictures:
![image](https://github.com/user-attachments/assets/89f826d6-745c-4b38-be03-4a4a2da3a63c)
![image](https://github.com/user-attachments/assets/e1148a70-ef82-48f9-9ee3-ca9f43f49486)

**Comment by Friskzips** [comment]
ops sorry github wasnt sending me the notification i am gonna fix it today
