### ISSUE TITLE
Clarify how the intensity config works.

### ISSUE THREAD

**Issue by juicyslew** [Friskzips/Lc-True-Darkness#2]
The current description is not adequate for figuring out what number I should be putting in if I want to change how dark it gets.

**Comment by Friskzips** [comment]
emh what do you mean? with that config you change 
the night vision intensity if its at 0 you are not gonna see anything, every number works to make it darker than vanilla as long as its less than the vanilla value(366,9317)

**Comment by juicyslew** [comment]
What is this number: 366,9317?  I don't understand what that number is and don't have any sense for what number to put to get a desired effect.  Additionally, is the effect linear?
Is it perhaps meant to be 366.9317?  If that's the case, and this is due to a different type of formatting where the decimal is a comma instead, maybe just round it for clarity, like "367"

**Comment by Friskzips** [comment]
closed because we discussed it on discord if someone want the answer
![Screenshot 2024-08-30 134142](https://github.com/user-attachments/assets/e569f119-1c32-4e2f-b34c-1c0c71f98c10)
